version: "3.5"
networks:
  my-network:
    driver: bridge

services:
  hazelcast-api:
    networks: ["my-network"]
    build: .
    ports:
      - "8080:8080"

  prometheus:
    networks: ["my-network"]
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./docker-compose/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - hazelcast-api

  grafana:
    networks: ["my-network"]
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
